web2/Models/ErrorViewModel.cs
namespace web2.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

web2/Models/IProcutoRepository.cs
using web2.Models;

namespace web2.Pepositories;
public interface IProdutoRepository
{
  void SaveProdutos(List<Livro> livros);
  IList<Produto> GetProdutos();
}

web2/Models/UpdateQuantidadeResponse.cs
using web2.Models.ViewModels;

namespace web2.Models;

public class UpdateQuantidadeResponse
{
  public ItemPedido? ItemPedido { get; }
  public CarrinhoViewModel? CarrinhoViewModel { get; }
  public UpdateQuantidadeResponse(ItemPedido itemPeidido, CarrinhoViewModel carrinhoViewModel)
  {
    ItemPedido = itemPeidido;
    CarrinhoViewModel = carrinhoViewModel;
  }
}

web2/Models/ViewModels/CarrinhoViewModel.cs
namespace web2.Models.ViewModels;

public class CarrinhoViewModel
{
  public IList<ItemPedido> Itens { get; }
  public CarrinhoViewModel(IList<ItemPedido> itens)
  {
    Itens = itens;
  }

  public decimal Total => Itens.Sum(i => i.Quantidade * i.PrecoUnitario);
}

web2/Models/modelo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading.Tasks;

namespace web2.Models
{
  [DataContract]
  public class BaseModel
  {
    [DataMember]
    public int Id { get; protected set; }
  }

  public class Produto : BaseModel
  {
    public Produto()
    {

    }

    [Required]
    public string Codigo { get; private set; } = String.Empty;
    [Required]
    public string Nome { get; private set; } = String.Empty;
    [Required]
    public decimal Preco { get; private set; }

    public Produto(string codigo, string nome, decimal preco)
    {
      this.Codigo = codigo;
      this.Nome = nome;
      this.Preco = preco;
    }
  }

  public class Cadastro : BaseModel
  {
    public Cadastro()
    {
    }

    public virtual Pedido? Pedido { get; set; }
    [MinLength(5, ErrorMessage = "Nome deve ter no mínimo 5 caracteres")]
    [MaxLength(50, ErrorMessage = "Nome deve ter no máximo 50 caracteres")]
    [Required(ErrorMessage = "Nome é obrigatório")]
    public string Nome { get; set; } = "";

    [Required(ErrorMessage = "Email é obrigatório")]
    public string Email { get; set; } = "";
    [Required(ErrorMessage = "Telefone é obrigatório")]
    public string Telefone { get; set; } = "";

    [Required(ErrorMessage = "Endereco é obrigatório")]
    public string Endereco { get; set; } = "";

    [Required(ErrorMessage = "Complemento é obrigatório")]
    public string Complemento { get; set; } = "";

    [Required(ErrorMessage = "Bairro é obrigatório")]
    public string Bairro { get; set; } = "";

    [Required(ErrorMessage = "Município é obrigatório")]
    public string Municipio { get; set; } = "";
    [Required(ErrorMessage = "UF é obrigatório")]
    public string UF { get; set; } = "";
    [Required(ErrorMessage = "CEP é obrigatório")]
    public string CEP { get; set; } = "";

    internal void Update(Cadastro novoCadastro)
    {
      this.Bairro = novoCadastro.Bairro;
      this.CEP = novoCadastro.CEP;
      this.Email = novoCadastro.Email;
      this.Endereco = novoCadastro.Endereco;
      this.Municipio = novoCadastro.Municipio;
      this.Nome = novoCadastro.Nome;
      this.Telefone = novoCadastro.Telefone;
      this.UF = novoCadastro.UF;

    }
  }

  [DataContract]
  public class ItemPedido : BaseModel
  {
    [Required]
    [DataMember]
    public Pedido? Pedido { get; private set; }

    [Required]
    [DataMember]
    public Produto? Produto { get; private set; }

    [Required]
    [DataMember]
    public int Quantidade { get; private set; }

    [Required]
    [DataMember]
    public decimal PrecoUnitario { get; private set; }
    [DataMember]
    public decimal Subtotal => Quantidade * PrecoUnitario;

    public ItemPedido()
    {

    }

    public ItemPedido(Pedido pedido, Produto produto, int quantidade, decimal precoUnitario)
    {
      Pedido = pedido;
      Produto = produto;
      Quantidade = quantidade;
      PrecoUnitario = precoUnitario;
    }

    internal void AtualizaQuantidade(int quantidade)
    {
      Quantidade = quantidade;
    }
  }

  public class Pedido : BaseModel
  {
    public Pedido()
    {
      Cadastro = new Cadastro();
    }

    public Pedido(Cadastro cadastro)
    {
      Cadastro = cadastro;
    }

    public List<ItemPedido> Itens { get; private set; } = new List<ItemPedido>();
    [Required]
    public virtual Cadastro Cadastro { get; private set; }
    public int CadastroId { get; set; }
  }
}

web2/Controllers/PedidoController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using web2.Models;
using web2.Models.ViewModels;
using web2.Pepositories;

namespace web2.Controllers;

public class PedidoController : Controller
{
  private readonly ILogger<PedidoController> _logger;
  private readonly IProdutoRepository _produtoRepository;
  private readonly IPedidoRepository _pedidoRepository;
  private readonly IItemPedidoRepository _itemRepository;
  public PedidoController(ILogger<PedidoController> logger, IProdutoRepository produtoRepository, IPedidoRepository pedidoRepository, IItemPedidoRepository itemRepository)
  {
    _logger = logger;
    _produtoRepository = produtoRepository;
    _pedidoRepository = pedidoRepository;
    _itemRepository = itemRepository;
  }

  public IActionResult Carrossel()
  {
    return View(_produtoRepository.GetProdutos());
  }
  public IActionResult Carrinho(string codigo)
  {
    if (!String.IsNullOrEmpty(codigo))
    {
      _pedidoRepository.AddItem(codigo);
    }

    var itens = _pedidoRepository.GetPedido().Itens;
    CarrinhoViewModel carrinhoViewModel = new CarrinhoViewModel(itens);
    return View(carrinhoViewModel);

  }
  public IActionResult Cadastro()
  {
    var pedido = _pedidoRepository.GetPedido();

    if (pedido == null) return RedirectToAction("Carrossel");

    return View(pedido.Cadastro);
  }

  [HttpPost]
  [ValidateAntiForgeryToken]
  public IActionResult Resumo(Cadastro cadastro)
  {
    if (ModelState.IsValid) return View(_pedidoRepository.UpdateCadastro(cadastro));

    return RedirectToAction("Cadastro");
  }

  [HttpPost]
  [ValidateAntiForgeryToken]
  public UpdateQuantidadeResponse UpdateQuantidade([FromBody] ItemPedido itemPedido)
  {
    System.Console.WriteLine($"Id: {itemPedido.Id}, Quantidade: {itemPedido.Quantidade}");
    return _pedidoRepository.UpdateQuantidade(itemPedido);
  }
}

web2/Views/Pedido/Cadastro.cshtml
@{
    ViewData["Title"] = "Cadastro";
}

@model Cadastro

<h3>Cadastro</h3>

<form asp-action="resumo" method="post">

    <div class="card card-body container">
        <div class="row g-3">
            <div class="row">
            <div class="col">
                <div class="form-group">
                    <label class="control-label" for="nomeCliente">Nome do Cliente</label>
                    <input type="text" class="form-control" id="nomeCliente" placeholder="Nome do Cliente"
                        asp-for="@Model.Nome"
                    >
                    <span asp-validation-for="@Model.Nome" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label" for="email">Email</label>
                    <input type="email" class="form-control" id="email" placeholder="Email"
                        asp-for="@Model.Email"
                    >
                     <span asp-validation-for="@Model.Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label" for="telefone">Telefone</label>
                    <input type="text" class="form-control" id="telefone" placeholder="Telefone"
                        asp-for="@Model.Telefone"
                    >
                     <span asp-validation-for="@Model.Telefone" class="text-danger"></span>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label class="control-label" for="endereco">Endereço</label>
                    <input type="text" class="form-control" id="endereco" placeholder="Endereço"
                        asp-for="@Model.Endereco"
                    >
                     <span asp-validation-for="@Model.Endereco" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label" for="complemento">Complemento</label>
                    <input type="text" class="form-control" id="complemento" placeholder="Complemento"
                        asp-for="@Model.Complemento"
                    >
                     <span asp-validation-for="@Model.Complemento" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label" for="bairro">Bairro</label>
                    <input type="text" class="form-control" id="bairro" placeholder="Bairro"
                        asp-for="@Model.Bairro"
                    >
                     <span asp-validation-for="@Model.Bairro" class="text-danger"></span>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label class="control-label" for="municipio">Município</label>
                    <input type="text" class="form-control" id="municipio" placeholder="Município"
                        asp-for="@Model.Municipio"
                    >
                     <span asp-validation-for="@Model.Municipio" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label" for="UF">UF</label>
                    <select class="form-control single-select" name="UF" 
                        asp-for="@Model.UF"
                    >
                        <option selected value="">[Selecione o estado]</option>
                        <option value="AC">Acre</option>
                        <option value="AL">Alagoas</option>
                        <option value="AP">Amapá</option>
                        <option value="AM">Amazonas</option>
                        <option value="BA">Bahia</option>
                        <option value="CE">Ceará</option>
                        <option value="DF">Distrito Federal</option>
                        <option value="ES">Espírito Santo</option>
                        <option value="GO">Goiás</option>
                        <option value="MA">Maranhão</option>
                        <option value="MT">Mato Grosso</option>
                        <option value="MS">Mato Grosso do Sul</option>
                        <option value="MG">Minas Gerais</option>
                        <option value="PA">Pará</option>
                        <option value="PB">Paraíba</option>
                        <option value="PR">Paraná</option>
                        <option value="PE">Pernambuco</option>
                        <option value="PI">Piauí</option>
                        <option value="RJ">Rio de Janeiro</option>
                        <option value="RN">Rio Grande do Norte</option>
                        <option value="RS">Rio Grande do Sul</option>
                        <option value="RO">Rondônia</option>
                        <option value="RR">Roraima</option>
                        <option value="SC">Santa Catarina</option>
                        <option value="SP">São Paulo</option>
                        <option value="SE">Sergipe</option>
                        <option value="TO">Tocantins</option>
                    </select>
                    <span asp-validation-for="@Model.UF" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label" for="cep">CEP</label>
                    <input type="text" class="form-control" id="cep" placeholder="CEP"
                        asp-for="@Model.CEP"
                    >
                    <span asp-validation-for="@Model.CEP" class="text-danger"></span>
                </div>
                <div class="col-auto card-body">
                    <a class="btn btn-success" asp-action="carrossel">
                        Continuar Comprando
                    </a>
                </div>
                <div class="form-group card-body">
                    <button type="submit"
                            class="btn btn-success">
                        Finalizar Pedido
                    </button>
                </div>
            </div>
            </div>
        </div>
    </div>

</form>

web2/Views/Pedido/Carrinho.cshtml
@{
    ViewData["Title"] = "Carrinho";
}

@model CarrinhoViewModel;       

<h3>Meu Carrinho</h3>

<form method="post" asp-action="carrinho">
</form>

<div class="card ">
    <div class="card-body">

        <div class="row">
            <div class="col-md-6">
                Item
            </div>
            <div class="col-md-2 text-center">
                Preço Unitário
            </div>
            <div class="col-md-2 text-center">
                Quantidade
            </div>
            <div class="col-md-2">
                <span class="pull-right">
                    Subtotal
                </span>
            </div>
        </div>
    </div>
    <div class="card-body">

    @foreach (var item in Model.Itens)
    {
        <div class="row row-center linha-produto" item-id="@item.Id">
            <div class="col-md-3">
                <img class="img-produto-carrinho" src="/img/produtos/large_@(item.Produto.Codigo).jpg" />
            </div>
            <div class="col-md-3">@item.Produto.Nome</div>
            <div class="col-md-2 text-center">R$ @item.PrecoUnitario</div>
            <div class="col-md-2 text-center">
                <div class="input-group">
                    
                    <button class="btn btn-outline-primary"
                        onclick="carrinho.clickDecremento(this)"
                    >
                        <span class="bi bi-caret-down"></span>
                    </button>
                   
                    <input type="text" value="@(item.Quantidade)"
                        onblur="carrinho.updateQuantidade(this)"
                        class="form-control text-center" />
                   
                    <button class="btn btn-outline-primary"
                        onclick="carrinho.clickIncremento(this)"
                    >
                        <span class="bi bi-caret-up"></span>
                    </button>
                    
                </div>
            </div>
            <div class="col-md-2">
                R$ <span class="pull-right" subtotal>
                    @(item.Quantidade * item.PrecoUnitario)
                </span>
            </div>
        </div>
    }
     

    </div>
    <div class="card-secondary">
        <div class="row">
            <div class="col-md-10">
                <span numero-itens>
                    Total: @(Model.Itens.Count())
                    itens
                </span>
            </div>
            <div class="col-md-2">
                Total: R$ <span class="pull-right" total>
                    @(Model.Total)
                </span>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="pull-right">
            <a class="btn btn-success" asp-controller="pedido"  asp-action="carrossel">
                Adicionar Produtos
            </a>
            <a class="btn btn-success"  asp-controller="pedido"  asp-action="cadastro">
                Preencher Cadastro
            </a>
        </div>
    </div>
</div>

@section Scripts
{
    <script src="~/js/carrinho.js">
    </script>
}

web2/Views/Pedido/Carrossel.cshtml
@{
    ViewData["Title"] = "Carrossel";
}
@model List<Produto>;

<h3>Catálogo</h3>

<div id="my-carousel" class="carousel slide" data-bs-ride="carousel">
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

        @{
            const int  TAMANHO_PAGINA =4;

            int paginas = (int)Math.Ceiling((double)Model.Count() / TAMANHO_PAGINA);
        }
        @for(int pagina = 0; pagina < paginas; pagina++)
        {   
            //controla a exibição do carrocel
            <section class="carousel-item @(pagina == 0 ? "active" : "" ) ">
                <div class="row">

                    @{
                        var produtosDaPagina = Model.Skip(pagina * TAMANHO_PAGINA).Take(TAMANHO_PAGINA);
                    }

                    @foreach(var produto in produtosDaPagina)
                    {
                        <div class="col-md-3 col-sm-3 col-lg-3 ">
                            <div class="card card-body">
                                <div class="card-primary">
                                    <img class="img-produto-carrossel" src="/img/produtos/large_@(produto.Codigo).jpg" />
                                </div>
                                <div class="card-secondary produto-footer">
                                    <div class="produto-nome">@produto.Nome</div>
                                    <div><h4><strong>R$ @produto.Preco</strong></h4></div>
                                    <div class="text-center">
                                        @* utilizando taghelpers *@
                                        <a  
                                            asp-controller="pedido" 
                                            asp-action="carrinho"
                                            asp-route-codigo="@produto.Codigo"
                                            class="btn btn-success">Adicionar</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
            
                </div>
            </section>
        }

    </div>

    <!-- Controls -->
    <button class="carousel-control-prev " type="button" data-bs-target="#my-carousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>

    <button class="carousel-control-next " type="button" data-bs-target="#my-carousel" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>

</div>

web2/Views/Pedido/Resumo.cshtml
@{
    ViewData["Title"] = "Resumo";
}
@model Pedido;

<h3>Resumo do Pedido</h3>

<div class="card card-body">
    <div class="card-primary">
        <div class="row">
            <div class="col-md-12">
                <h3>Nº do Pedido: @(Model.Id)</h3>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-md-3">
                <h3>Seus Dados</h3>
                <div>(@Model.Cadastro.Nome)</div>
                <div>(@Model.Cadastro.Telefone)</div>
            </div>
            <div class="col-md-3">
                @Model.Cadastro.Email
            </div>
            <div class="col-md-6">
                <h3>Endereço de Entrega</h3>
                <div>@Model.Cadastro.Endereco @Model.Cadastro.Complemento - @Model.Cadastro.Bairro - CEP:  @Model.Cadastro.CEP - @Model.Cadastro.Municipio - @Model.Cadastro.UF - Brasil</div>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-md-10">
                <h3>Item</h3>
            </div>
            <div class="col-md-2">
                <h3>Quantidade</h3>
            </div>
        </div>
    @foreach(var item in Model.Itens)
    {
        <div class="row">
            <div class="col-md-10">
                <div>@item.Produto.Nome</div>
            </div>
            <div class="col-md-2">
                <div class="pull-right">@item.Quantidade</div>
            </div>
        </div>
    }
   
    </div>
</div>

web2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - web2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/web2.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</head>

<body>
    <header>
     <nav class="navbar navbar-expand-lg navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" hasp-area="" asp-controller="Pedido" asp-action="Carrossel"></a>
            </div>
        </nav>
    </header>
    <div class="container container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top text-muted">
        <div class="container text-center">
            &copy; 2022 - Casa do código 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>